spring:
  application:
    name: Ecommerce

  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:mem:test

  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: true

project:
  image: images/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  info:
    env:
      enabled: true

info:
  app:
    name: Ecommerce API
    description: Spring Boot ecommerce backend
    version: 0.0.1-SNAPSHOT
