spring:
  application:
    name: user-service

  data:
    mongodb:
      uri: mongodb://${MONGO_HOST:localhost}:${MONGO_PORT:27017}/${MONGO_DB:ecommerce_users}

services:
  product-service: ${PRODUCT_SERVICE_URL:http://localhost:8082}

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  info:
    env:
      enabled: true

info:
  app:
    name: User Service
    version: 0.0.1-SNAPSHOT
